doc(audits): cantina report
morpho-org/pre-liquidation pull request #88
Opened 2024-10-31 15:34 UTC by peyha

2024-10-31 17:17 UTC, MathisGD requested changes
- please put the date as [here](https://github.com/morpho-org/morpho-blue/tree/main/audits)
- and this was a spearbit audit, not cantina managed

2024-11-04 09:02 UTC, MathisGD submitted a review, later dismissed

2024-11-04 10:03 UTC, QGarchery commented on audits/2024-10-30-pre-liquidation-ABDK.pdf
They seem to show 1st November as the date of the audit:
![Screenshot from 2024-11-04 11-01-15](https://github.com/user-attachments/assets/7595974b-ec15-414b-ab05-2e19e8692cc8)
Also the full name of the auditing company is ABDK Consulting, so maybe we could use that ?

2024-11-04 10:15 UTC, peyha commented on audits/2024-10-30-pre-liquidation-ABDK.pdf
You are right, I initially used the date when we received the report

2024-11-04 10:21 UTC, QGarchery approved these changes

2024-11-04 10:24 UTC, MathisGD approved these changes

2024-11-04 10:36 UTC, merged